#!/usr/bin/env bash

source require-colors

if [ "$(id -u)" -ne 0 ]; then
    echo "${C_RED}ERROR: This script must be run with root privileges.${C_RESET}" >&2
    echo "${C_RED}TRY: sudo $0${C_RESET}" >&2
    exit 1
fi
